#!/usr/bin/env python3
"""Generate include/constants/{flags,vars}_kanto.h for the combined Hoenn + Kanto build.

Upstream expansion builds Hoenn (emerald) or Kanto (firered), never both. Each game's
flag header stubs the other game's flag names to 0, and Kanto vars share Hoenn's
0x4000-0x40FF range. This script moves every Kanto-only flag/var into its own range
in the Emerald build:
  flags: KANTO_FLAGS_START + <FireRed value>   (Hoenn flags end at 0x95F)
  vars:  <FireRed value> + 0x100               (0x4110-0x41FF)
Names both games really use (badges, FLAG_SYS_*, ...) keep their Hoenn value; see
design/todo.md. Re-run after merging upstream: python3 hack_scripts/gen_kanto_constants.py
"""
import re, subprocess, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
CC = "arm-none-eabi-gcc"

def names_in(path):
    out = []
    for line in open(path):
        m = re.match(r"\s*#define\s+(\w+)\s+\S", line)
        if m:
            out.append(m.group(1))
    return out

def evaluate(game, names, headers):
    src = "#include \"constants/global.h\"\n" + "".join(f'#include "constants/{h}"\n' for h in headers)
    src += "".join(f'@@ "{n}" = {n}\n' for n in names)
    pp = subprocess.run([CC, "-E", "-P", "-x", "c", "-", "-iquote", "include", "-DMODERN=1",
                         "-DTESTING=0", f"-D{game}", "-std=gnu17"],
                        input=src, capture_output=True, text=True, check=True).stdout
    vals = {}
    for line in pp.splitlines():
        if not line.startswith("@@ "):
            continue
        name, expr = line[3:].split(" = ", 1)
        name = name.strip('"')
        if name == expr:          # not defined in this game
            continue
        try:
            vals[name] = eval(expr.replace("/", "//"), {})
        except Exception:
            pass                  # not a numeric constant
    return vals

FLAG_SKIP = re.compile(r"(_START|_END|_COUNT|_H)$|^NUM_")

def gen_flags():
    names = sorted(set(names_in("include/constants/flags_frlg.h")) | set(names_in("include/constants/flags.h")))
    kanto = evaluate("FIRERED", names, ["flags.h"])
    hoenn = evaluate("EMERALD", names, ["flags.h"])
    hoenn_count = hoenn["FLAGS_COUNT"]
    kanto_count = kanto["FLAGS_COUNT"]
    start = (hoenn_count + 7) // 8 * 8
    moved = [n for n in sorted(kanto, key=lambda n: (kanto[n], n))
             if n.startswith("FLAG_") and not FLAG_SKIP.search(n)
             and 0 < kanto[n] < kanto_count and hoenn.get(n, 0) == 0]
    lines = [
        "// Generated by hack_scripts/gen_kanto_constants.py. Do not edit by hand.",
        "// Kanto-only flags, moved above Hoenn's flags for the combined build.",
        "#ifndef GUARD_CONSTANTS_FLAGS_KANTO_H",
        "#define GUARD_CONSTANTS_FLAGS_KANTO_H",
        "",
        f"#define KANTO_FLAGS_START 0x{start:X}",
        f"#define KANTO_FLAGS_END   (KANTO_FLAGS_START + 0x{kanto_count - 1:X})",
        "",
    ]
    for n in moved:
        lines += [f"#undef {n}", f"#define {n} (KANTO_FLAGS_START + 0x{kanto[n]:X})"]
    lines += ["", "#undef FLAGS_COUNT", "#define FLAGS_COUNT (KANTO_FLAGS_END + 1)", "",
              "#endif // GUARD_CONSTANTS_FLAGS_KANTO_H", ""]
    open("include/constants/flags_kanto.h", "w").write("\n".join(lines))
    return len(moved), start, start + kanto_count

def gen_vars():
    names = sorted(set(names_in("include/constants/vars_frlg.h")))
    kanto = evaluate("FIRERED", names, ["vars.h"])
    hoenn_names = set(names_in("include/constants/vars.h"))
    moved = [n for n in sorted(kanto, key=lambda n: (kanto[n], n))
             if n.startswith("VAR_") and n not in hoenn_names and 0x4010 <= kanto[n] <= 0x40FF]
    lines = [
        "// Generated by hack_scripts/gen_kanto_constants.py. Do not edit by hand.",
        "// Kanto-only vars, moved from 0x40xx to 0x41xx for the combined build.",
        "#ifndef GUARD_CONSTANTS_VARS_KANTO_H",
        "#define GUARD_CONSTANTS_VARS_KANTO_H",
        "",
    ]
    for n in moved:
        lines += [f"#undef {n}", f"#define {n} 0x{kanto[n] + 0x100:X}"]
    lines += ["", "#undef VARS_END", "#define VARS_END 0x41FF", "",
              "#endif // GUARD_CONSTANTS_VARS_KANTO_H", ""]
    open("include/constants/vars_kanto.h", "w").write("\n".join(lines))
    return len(moved)

if __name__ == "__main__":
    n, s, e = gen_flags()
    print(f"flags_kanto.h: {n} flags moved to 0x{s:X}-0x{e - 1:X}")
    print(f"vars_kanto.h: {gen_vars()} vars moved to 0x41xx")
